### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by tommyming**
This pull request aims to add SPM (swift package manager )support for the repo.
As the project seems no maintenance recently, please feel free to use my fork in case of SPM migration.

### CODE REVIEW

**Review by souzainf3 — APPROVED** [review]

**Comment by souzainf3** [comment]
Thanks @tommyming.

**Comment by tommyming** [comment]
@souzainf3 I think we may need to open an issue/a new PR about the naming inside Package.swift.

I have added `SPM` suffix to the package.swift in my fork, which I thought the repository is not maintained recently.
In case for an proper update, a new PR is needed for updating the naming.

**Comment by souzainf3** [comment]
Hi @tommyming.
The last release `6.1.0` added officially the SPM support.
The package is renamed to `RNLoadingButton`, following the Swift style, prefix only in the Package e the class is renamed to `LoadingButton`

Thanks for your help.

**Comment by tommyming** [comment]
@souzainf3 Many thanks, LGTM! :)

**Pull request merged**
